on:
  workflow_run:
    workflows: ["multi-build", "build-custom-image"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      manual-tag:
        description: 'Manual Tag'
        required: false
        default: 'main'
        type: string
      ghost_version:
        description: 'Ghost version'
        required: false
        default: '5.81.1'

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  IMAGE_SHA: ${{ github.event.action.outputs.IMAGE_SHA }}
  IMAGE_TAG: ${{ github.event.workflow_run.event.inputs.manual-tag }}

  
jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: show env
        run: |
          echo "GHCR_IMAGE=${GHCR_IMAGE}"
          echo "IMAGE_SHA=${IMAGE_SHA}"
          echo "IMAGE_TAG=${IMAGE_TAG}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: false
        with:
          image-ref: "${{ env.GHCR_IMAGE }}:${{ env.IMAGE_TAG }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          scan-type: 'image'
          github-pat: '${{ github.token }}'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'

          


      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        continue-on-error: false
        with:
          sarif_file: 'trivy-results.sarif'
          
